# Generated by Django 5.0.3 on 2024-03-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainer_task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
