# Generated by Django 5.0.3 on 2024-03-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainer_task_app', '0002_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='brainer_task_app.company'),
        ),
    ]
